fix: add missing fix in apim changelog
gravitee-io/gravitee-platform-docs pull request #369
Opened 2024-12-05 18:02 UTC by Okhelifi

## Description

An issue is missing in the release changelog. Here is a pr to fix it

2024-12-17 13:55 UTC, phiz71 requested changes
opening square brackets need to be escaped

2024-12-17 13:55 UTC, phiz71 commented on docs/apim/4.2/overview/changelog/apim-4.2.x.md
> +* [gravitee-policy-cache] Timeouts occur when trying to cache a large payload [#10208](https://github.com/gravitee-io/issues/issues/10208)
```suggestion
* \[gravitee-policy-cache] Timeouts occur when trying to cache a large payload [#10208](https://github.com/gravitee-io/issues/issues/10208)
```

2024-12-17 13:55 UTC, phiz71 commented on docs/apim/4.3/overview/changelog/apim-4.3.x.md
> +* [gravitee-policy-cache] Timeouts occur when trying to cache a large payload [#10208](https://github.com/gravitee-io/issues/issues/10208)
```suggestion
* \[gravitee-policy-cache] Timeouts occur when trying to cache a large payload [#10208](https://github.com/gravitee-io/issues/issues/10208)
```

2024-12-17 13:55 UTC, phiz71 commented on docs/apim/4.4/overview/changelog/apim-4.4.x.md
> +* [gravitee-policy-cache] Timeouts occur when trying to cache a large payload [#10208](https://github.com/gravitee-io/issues/issues/10208)
```suggestion
* \[gravitee-policy-cache] Timeouts occur when trying to cache a large payload [#10208](https://github.com/gravitee-io/issues/issues/10208)
```

2024-12-17 13:55 UTC, phiz71 commented on docs/apim/4.5/overview/changelog/apim-4.5.x.md
> +* [gravitee-policy-cache] Timeouts occur when trying to cache a large payload [#10208](https://github.com/gravitee-io/issues/issues/10208)
```suggestion
* \[gravitee-policy-cache] Timeouts occur when trying to cache a large payload [#10208](https://github.com/gravitee-io/issues/issues/10208)
```

2024-12-20 17:39 UTC, Lyd1aCla1r3 approved these changes

2024-12-23 08:52 UTC, phiz71 approved these changes

2025-01-06 08:19 UTC, merged