feat: update doc about AM upgrade installation on redhat
gravitee-io/gravitee-platform-docs pull request #71
Opened 2023-11-29 11:15 UTC by passionne

**Issue**

https://gravitee.atlassian.net/browse/DV-309

**Description**

feat: update doc about APIM upgrade installation on redhat

2023-11-30 10:42 UTC, leleueri requested changes

2023-11-30 10:42 UTC, leleueri commented on docs/am/4.0/getting-started/install-and-upgrade-guides/install-on-red-hat.md
> +Since maintained version 4.0.6 and above the rpm upgrade of APIM component is easier. Now you can simply upgrade and restart AM.
```suggestion
Since maintained version 4.0.6 and above the rpm upgrade of AM component is easier. Now you can simply upgrade and restart AM.
```

2023-11-30 10:42 UTC, leleueri commented on docs/am/4.1/getting-started/install-and-upgrade-guides/install-on-red-hat.md
> +Since maintained version 4.1.8 and above the rpm upgrade of APIM component is easier. Now you can simply upgrade and restart AM.
```suggestion
Since maintained version 4.1.8 and above the rpm upgrade of AM component is easier. Now you can simply upgrade and restart AM.
```

2023-12-01 16:01 UTC, passionne commented on docs/am/4.0/getting-started/install-and-upgrade-guides/install-on-red-hat.md
> +Since maintained version 4.0.6 and above the rpm upgrade of APIM component is easier. Now you can simply upgrade and restart AM.
fixed... I am so so sorry

2023-12-01 16:01 UTC, passionne commented on docs/am/4.1/getting-started/install-and-upgrade-guides/install-on-red-hat.md
> +Since maintained version 4.1.8 and above the rpm upgrade of APIM component is easier. Now you can simply upgrade and restart AM.
fixed... I am so so sorry

2023-12-01 16:03 UTC, leleueri approved these changes

2023-12-13 16:30 UTC, Lyd1aCla1r3 approved these changes

2023-12-13 16:30 UTC, merged